### ISSUE TITLE
Grid Layout 

### ISSUE THREAD

**Issue by saltsoftdrink** [DennisBauer/RecurringExpenseTracker#117]
If possible add grid layout cuz I've too many things to add and it becomes to exhausting while scrolling in list

**Comment by abGit9** [comment]
can you post a screenshot?

**Comment by abGit9** [comment]
Hi, I played around with using grids to make a more compact view of the expenses. This is a rough UI mockup. Maybe we should provide an additional option of viewing expenses in a grid format. Also, it could help to add variation in fonts between different types of information (ex - name vs price) to make each piece of info stand out from the rest and easier to read. Just some ideas...


Current UI - Main_Activity: 

![Current UI - Main_Activity](https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/1d8c5296-7b10-4b31-a059-b4b3b7d446ff)


-----------------------------------------
UI mockup(Grid) - Main_Activity


![UI mockup(Grid) - Main_Activity](https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/1dd6004c-9ee1-40d4-9fda-ef9e91d1e6dd)

**Comment by abGit9** [comment]
2-UI mockup(Grid) - Main_Activity: 

![2-UI mockup(Grid) - Main_Activity](https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/07ccb59a-fbe3-458f-b798-b0f89f4563e9)

**Comment by abGit9** [comment]
Cool, that's great. Do you think grid would be ok for mobile as well? Might me a more efficient use of space to display info.

**Comment by abGit9** [comment]
Thanks. I am new to this project. Can I contribute? How should I  go about it? Should i keep providing screenshots of my ideas and  progress, or should I just submit an issue or pull request?

**Comment by abGit9** [comment]
Putting a grid action in the app bar is a good idea. It all sounds good. I'll work on it. Thanks.

**Comment by abGit9** [comment]
hey man, sorry been busy. Gonna work on it.  Cool if i update you in a few days?

**Comment by abGit9** [comment]
here is a mockup....
https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/3430f48c-fd1f-490c-b28a-49f57c45d076

**Comment by abGit9** [comment]
Added some animations, let me know what you think. Thanks. 

https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/5d4a46c6-7dce-43cf-b8f4-657018c0c56c

**Comment by abGit9** [comment]
Sure. Will do. 👍. I'll get back to u.

**Comment by abGit9** [comment]
> > Added some animations, let me know what you think. Thanks.
> > Grid.UI.Mockup.2.mp4
> 
> Bro really that's great, btw I'm new to Android can you give resources from where did you learned kotlin concept. Add some padding to grid boxes to would be greater. Anyways I appreciate your work

Thanks for the comments . I'm new kotlin and jetpack as well but do know java and xml. So I just looked over a few sites to get a sense of the syntax....
https://www.w3schools.com/KOTLIN/index.php
https://developer.android.com/codelabs/jetpack-compose-state#0

Good luck!

**Comment by abGit9** [comment]
![Screenshot_20240223_172821_Expenses.jpg](https://github.com/DennisBauer/RecurringExpenseTracker/assets/50727486/97a9ecdd-f3b6-4707-b945-783f6f8477d6)

**Comment by abGit9** [comment]
Added your suggestions. I think at this point I can prepare a pull request. That way if it's merged we will ALL be able to fine tune the appearance(fonts, text size, color etc)

**Comment by abGit9** [comment]
Sound good?

**Comment by saltsoftdrink** [comment]
> Sound good?

Yes. Can you align items centre it will be ok for looks and then create a PR

**Comment by abGit9** [comment]
Thank you very much. Appreciate the collaboration.
