### ISSUE TITLE
New app name proposal

### ISSUE THREAD

**Issue by serrq** [DennisBauer/RecurringExpenseTracker#119]
Current name excess the characters lenght in launcher.

So actually I renamed it as "Expenses" to fill the app name field.

Do you have a better name?

**Comment by Scrambled777** [comment]
@DennisBauer Sorry, bit late. 
Since, this app only deals with recurring expenses so renaming it as `Expenses` might give impressions that it is a fully fledged money manager.

May I suggest `Recurrence` or something which reflects this app core feature.

**Comment by Scrambled777** [comment]
@DennisBauer @serrq 
Thanks for explanation. Cheers.
