### ISSUE TITLE
Option to change currency in settings

### ISSUE THREAD

**Issue by DennisBauer** [DennisBauer/RecurringExpenseTracker#12]
**Is your feature request related to a problem? Please describe.**
  
  
  **Describe the solution you'd like**
  
Have an option in the app settings to manually change the currency used.
  
  **Describe alternatives you've considered, if any**
  
  
  **Additional context**

**Comment by golden-peaches** [comment]
It would be great to have an option for a global default currency setting, **and** a setting for each expense to override the default currency. Of course, this would probably require converting between currencies in order to compute total expenses. Unless there is a way to display total expenses for the currencies used seperately.

**Comment by bartoszluka** [comment]
I can try to implement this feature.

my idea is to have another value in the settings page that changes the stored `Locale` value from `java.util.Locale`. then we can pass this value to the `getCurrencyString` extension method. 

it does not seem too complicated unless there are issues with `suspend fun`s which I don't quite understand

**Comment by bartoszluka** [comment]
I was really busy for the past months, I might be able to do it this week but feel free to implement this feature.

**Comment by saltsoftdrink** [comment]
> I was really busy for the past months, I might be able to do it this week but feel free to implement this feature.

Is there any update in the feature it's been a week

**Comment by bartoszluka** [comment]
@saltsoftdrink I am doing this right now

**Comment by gohilmehul** [comment]
fun Float.toCurrencyString(): String {
    val indianLocale = Locale("en", "IN")
    return NumberFormat.getCurrencyInstance(indianLocale).format(this)
}

I have implemented it in Extensions.kt class and it work.

**Comment by bartoszluka** [comment]
@gohilmehul this is ok but there is one issue. We have to get the current stored locale saved in storage, which makes this a `suspend fun` (or returns `Flow<T>`, I don't really remember and I am not that good at kotlin's `async` model). This prohibits the usage of a simple extension method to the `Float` type. This solution will not work in the general case.

**Comment by gevo507** [comment]
This should fix it i tried it and it work for me 
replace from line 9 to 12 in Extensions.kt with this code:

```
import java.util.Locale

fun Float.toCurrencyString(): String {
    val saudiLocale = Locale("ar", "SA") // Change this to ur country/Currency
    return NumberFormat.getCurrencyInstance(saudiLocale).format(this)
}

fun main() {
    val amount: Float = 1234.56f
    val currencyString: String = amount.toCurrencyString()
    println(currencyString)
}
```

the code should looks like this :
![Screenshot_14](https://github.com/DennisBauer/RecurringExpenseTracker/assets/52261530/dc69807f-950f-449d-8703-443766c6303e)

Don't forget to thank me

**Comment by saltsoftdrink** [comment]
> This should fix it i tried it and it work for me replace from line 9 to 12 in Extensions.kt with this code:
> 
> ```
> import java.util.Locale
> 
> fun Float.toCurrencyString(): String {
>     val saudiLocale = Locale("ar", "SA") // Change this to ur country/Currency
>     return NumberFormat.getCurrencyInstance(saudiLocale).format(this)
> }
> 
> fun main() {
>     val amount: Float = 1234.56f
>     val currencyString: String = amount.toCurrencyString()
>     println(currencyString)
> }
> ```
> 
> the code should looks like this : ![Screenshot_14](https://private-user-images.githubusercontent.com/52261530/339026484-dc69807f-950f-449d-8703-443766c6303e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNjEwOTcsIm5iZiI6MTcxODI2MDc5NywicGF0aCI6Ii81MjI2MTUzMC8zMzkwMjY0ODQtZGM2OTgwN2YtOTUwZi00NDlkLTg3MDMtNDQzNzY2YzYzMDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEzVDA2Mzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZGFiOWJhYmY4MmQyMzFmOTBkOTFkYjEzMDczZmVlNjlmOTIyYjRmYTdhMjJiMGQ1ZmMzZDYzMDkwOTNmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rGBj2MY9zr_Sn-ANqSHDeHjAxcYrcSmvpS1Th1XwBJY)
> 
> Don't forget to thank me

Thank you soooooo much ☺️
