### ISSUE TITLE
Implement backup and restore 

### ISSUE THREAD

**Issue by Outlet2048** [DennisBauer/RecurringExpenseTracker#25]
**Is your feature request related to a problem? Please describe.**
 Having to recreate everything when switching phones
 
  
  **Describe the solution you'd like**
A local backup to file 
  
  
  **Describe alternatives you've considered, if any**
Cloud backup
  
  
  **Additional context**
Backing up and importing from a backup file are very important to me if I actually want to use this app  
For now I have to stick to a closed source app for this reason

**Comment by DennisBauer** [comment]
@Outlet2048 for the first version I'll add a manual backup and restore option in the settings to a user specified directory. 
I created a follow up issue to create automated backups on changes. See #44
