### ISSUE TITLE
Expenses due tomorrow are shown as "today"

### ISSUE THREAD

**Issue by 825i** [DennisBauer/RecurringExpenseTracker#272]
**Android version(s):** 14

**Device model(s):** Xperia 1V

**Last working app version (if known):** 0.10.0

**Description of problem:**
Expenses shown as coming tomorrow day "Today" in the app

**Screenshot or video of problem:**

**Additional information:**

**Comment by DennisBauer** [comment]
@825i Thanks for reporting this bug. Indeed, I can reproduce this as well. Seams like this issue slipped in again. :wink:
I already fixed an issue with the time zone some months ago.
