### ISSUE TITLE
[Feature] Account for due dates in expense amount values

### ISSUE THREAD

**Issue by RequestPrivacy** [DennisBauer/RecurringExpenseTracker#38]
First thanks for the app, exactly that kind of specialized tracker I was looking for.
 
  **Is your feature request related to a problem? Please describe.**
  The feature request is regarding a missing function: right now the app displays the total expenses per year and splits it up in monthly and weekly fractions of that total sum.

In reality the costs incur in a  highly un-regular timely fashion (i.e. perhaps 2/3 of expenses in the beginning of the year, the rest in the second half). For planning on how much money one needs to "save" from each (weekly / monthly) paycheck the app has to consider the dates where the expenses are due.
  
  **Describe the solution you'd like**
Adding an expense should require an additional "date" field. The app then calculates on how much money from now on needs to be saved / send to an "expenses" account (either a real separate account or a "mental" one)  so that once the due date hits and the expenses are credited from the account there is enough money in it.

Suppose for example: 
  - Today is 2023-01-02 and I get my paycheck every first day of the month into bank account A
  - I make a monthly standing order in which I transfer a fixed amount to my expense account B
  - Expenses are credited from account B
  - Now a yearly expense is added with due date 2023-02-15 and $100
  - Time to first expense: 1 full month

Current way of displaying expense: $100 / 12 months = $ 8.3 per month
More realistic way of showing the expense: show a monthly expense of ($100 / 1 month remaining to due date) = $100 because if not the full $100 are present NEXT MONTH there isn't enough money in account B to honor the expense.

So now I know that I have to account for a $100 expense next month and from my paycheck that amount isn't available anymore. 

As an action I have to transfer $100 on top of my monthly standing order of $8.3 ( so that next month a total of $100+$8.3 is transferred from account A -> account B).

- On same day another expense gets added, a weekly one starting on 2023-02-18 with an amount of $5

Now I need not only to transfer ($100+$8.3)  to account B but ALL $5 expenses for the february period (2 full weeks) so that my account B is full funded for all expenses in february.

So now the app should show a $100+($5 per week*2 weeks) = $110 one time payment next month and a monthly standing order of ($8.3 + $5/week * 4 weeks) = $28.3.

  **Describe alternatives you've considered, if any**
  Not sure if there is an alternative, as that's just the way reality is.
  
  **Additional context**
- Some countries have their paycheck pay-out periods (weekly / monthly) and arriving on different times (every monday/thursday or every 25th of the month).
- Sometimes pay-out dates or expenses due date are on public holidays or weekends. There should be some safety buffer e.g. an expense account B should always already have a funding so that the expenses of this and next month are already covered.

**Comment by DennisBauer** [comment]
Thanks for the request. To summarize and recheck I get your idea:
You want to define a start / credit date for each expense. Then the app should calculate the exact money you need to pay for the current and next month depending on the start / credit date and the recurrense of the expense. Is this correct?
I like the idea of adding the start date of an expense and at least show the date of when the next occurrence is when you need to pay it again. Showing the monthly expense not divided by 12 but for exact months would need to be shown separately as I would like to keep the average values as well.

**Comment by RequestPrivacy** [comment]
> Then the app should calculate the exact money you need to pay for the current and next month depending on the start / credit date and the recurrense of the expense. Is this correct?

Yes, it should split up the expenses in a weekly/monthly/yearly average and potential one time payments for the coming week/month/year so that at all times your account is funded enough to cover all expenses.

I guess the easiest way to think about it is imagining an hypothetical account from which all expenses are deducted and which receives one time and/or fixed interval money inflows. Expenses are deducted according to their dates. The account balance should never fall under 0. 

Now, show the user how much he must send to that account a) according to his inflow and expenditure interval regularly and b) in one time payments to satisfy that the account never runs out of money.
